### ISSUE TITLE
"no such column" errors running locally

### ISSUE THREAD

**Issue by edenlightning** [Lightning-AI/lightning-hpo#124]
`lightning run app training_studio_app.py`

`Your Lightning App is starting. This won't take long.
INFO: Your app has started. View it in your browser: http://127.0.0.1:7501/view
Creating the following tables [<class 'lightning_hpo.commands.sweep.run.SweepConfig'>, <class 'lightning_hpo.commands.notebook.run.NotebookConfig'>, <class 'lightning_hpo.commands.tensorboard.stop.TensorboardConfig'>]
 * Serving Flask app 'lightning_hpo.components.servers.file_server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:59908
Press CTRL+C to quit
127.0.0.1 - - [13/Sep/2022 18:12:02] "GET / HTTP/1.1" 200 -
The Training Studio App is ready ! Database URL: http://127.0.0.1:59905
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: notebookconfig.start_time

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/edenafek/lightning-hpo/lightning_hpo/components/servers/db/server.py", line 19, in general_get
    results = session.exec(statement)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlmodel/orm/session.py", line 60, in exec
    results = super().execute(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: notebookconfig.start_time
[SQL: SELECT notebookconfig.requirements, notebookconfig.notebook_name, notebookconfig.cloud_compute, notebookconfig.stage, notebookconfig.desired_stage, notebookconfig.url, notebookconfig.start_time 
FROM notebookconfig]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: notebookconfig.start_time

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/edenafek/lightning-hpo/lightning_hpo/components/servers/db/server.py", line 19, in general_get
    results = session.exec(statement)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlmodel/orm/session.py", line 60, in exec
    results = super().execute(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: notebookconfig.start_time
[SQL: SELECT notebookconfig.requirements, notebookconfig.notebook_name, notebookconfig.cloud_compute, notebookconfig.stage, notebookconfig.desired_stage, notebookconfig.url, notebookconfig.start_time 
FROM notebookconfig]
(Background on this error at: https://sqlalche.me/e/14/e3q8)`

**Comment by tchaton** [comment]
Hey @edenlightning,

You are running an old version of the App and the database spec has changed.

You would need to run `rm database.db` to delete the database.

I added a warning in the docs.

<img width="1041" alt="Screenshot 2022-09-14 at 08 29 41" src="https://user-images.githubusercontent.com/12861981/190076858-22f26880-3d45-4361-b473-19782a7309bf.png">
