### ISSUE TITLE
'Logger' object has no attribute 'warning' error running on the cloud

### ISSUE THREAD

**Issue by edenlightning** [Lightning-AI/lightning-hpo#125]
`lightning run app training_studio_app.py --cloud`

Your Lightning App is starting. This won't take long.
Traceback (most recent call last):
  File "/Users/edenafek/opt/anaconda3/envs/studio/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/lightning_app/cli/lightning_cli.py", line 73, in main
    _main()
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/lightning_app/cli/lightning_cli.py", line 387, in run_app
    _run_app(file, cloud, cluster_id, without_server, no_cache, name, blocking, open_ui, env)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/lightning_app/cli/lightning_cli.py", line 328, in _run_app
    dispatch(
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/lightning_app/runners/runtime.py", line 65, in dispatch
    return runtime.dispatch(on_before_run=on_before_run, name=name, no_cache=no_cache, cluster_id=cluster_id)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/lightning_app/runners/cloud.py", line 87, in dispatch
    self._check_uploaded_folder(root, repo)
  File "/Users/edenafek/opt/anaconda3/envs/studio/lib/python3.9/site-packages/lightning_app/runners/cloud.py", line 345, in _check_uploaded_folder
    logger.warning(warning_msg)
AttributeError: 'Logger' object has no attribute 'warning'

**Comment by tchaton** [comment]
Fixed there: https://github.com/Lightning-AI/lightning/pull/14696

**Comment by ethanwharris** [comment]
Should be fixed now
