### ISSUE TITLE
Not able to connnect to app

### ISSUE THREAD

**Issue by edenlightning** [Lightning-AI/lightning-hpo#228]
Tried to clone app from gallery and connect
got the following error:
```Installing missing `lightning_hpo` requirement.

Storing `delete sweep` at /Users/edenafek/.lightning/lightning_connection/2462/commands/delete_sweep.py
Traceback (most recent call last):
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/lightning/app/cli/lightning_cli.py", line 70, in main
    _main()
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/lightning/app/utilities/exceptions.py", line 36, in invoke
    return super().invoke(ctx)
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/lightning/app/cli/commands/connection.py", line 147, in connect
    _download_command(
  File "/Users/edenafek/opt/anaconda3/envs/prod-16117/lib/python3.10/site-packages/lightning/app/utilities/commands/base.py", line 126, in _download_command
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/edenafek/.lightning/lightning_connection/2462/commands/run_sweep.py", line 11, in <module>
    from hydra.core.override_parser.overrides_parser import OverridesParser
ModuleNotFoundError: No module named 'hydra'
```

**Comment by lantiga** [comment]
I know what it is: the pip package published on pypi is not up to date, so it doesn't include the hydra dependency. We need to make a release on pypi.
