### ISSUE TITLE
Cannot run example_1 on cloud

### ISSUE THREAD

**Issue by manskx** [Lightning-AI/lightning-hpo#46]
## 🐛 Bug

error:

```
[flow] 2022-09-01T08:53:04.580Z ERROR: Found an exception when loading your application from examples/1_app_agnostic.py. Please, resolve it to run your app.
[flow] 2022-09-01T08:53:04.580Z Traceback (most recent call last):
[flow] 2022-09-01T08:53:04.580Z   File "examples/1_app_agnostic.py", line 5, in <module>
[flow] 2022-09-01T08:53:04.580Z     from lightning_hpo import Sweep
[flow] 2022-09-01T08:53:04.580Z   File "/content/venv/lib/python3.8/site-packages/lightning_hpo/__init__.py", line 22, in <module>
[flow] 2022-09-01T08:53:04.580Z     from lightning_hpo.components.sweep import Sweep  # noqa: E402
[flow] 2022-09-01T08:53:04.580Z   File "/content/venv/lib/python3.8/site-packages/lightning_hpo/components/sweep.py", line 5, in <module>
[flow] 2022-09-01T08:53:04.580Z     from lightning.app.components.python.tracer import Code
[flow] 2022-09-01T08:53:04.580Z ImportError: cannot import name 'Code' from 'lightning.app.components.python.tracer' (/content/venv/lib/python3.8/site-packages/lightning/app/components/python/tracer.py)
[flow] 2022-09-01T08:53:04.583Z ERROR: Found an exception when loading your application from examples/1_app_agnostic.py. Please, resolve it to run your app.
[flow] 2022-09-01T08:53:04.583Z Traceback (most recent call last):
[flow] 2022-09-01T08:53:04.583Z   File "examples/1_app_agnostic.py", line 5, in <module>
[flow] 2022-09-01T08:53:04.583Z     from lightning_hpo import Sweep
[flow] 2022-09-01T08:53:04.583Z   File "/content/venv/lib/python3.8/site-packages/lightning_hpo/__init__.py", line 22, in <module>
[flow] 2022-09-01T08:53:04.583Z     from lightning_hpo.components.sweep import Sweep  # noqa: E402
[flow] 2022-09-01T08:53:04.583Z   File "/content/venv/lib/python3.8/site-packages/lightning_hpo/components/sweep.py", line 5, in <module>
[flow] 2022-09-01T08:53:04.583Z     from lightning.app.components.python.tracer import Code
[flow] 2022-09-01T08:53:04.583Z ImportError: cannot import name 'Code' from 'lightning.app.components.python.tracer' (/content/venv/lib/python3.8/site-packages/lightning/app/components/python/tracer.py)
[flow] 2022-09-01T08:53:04.692Z ERROR: Found an exception when loading your application from examples/1_app_agnostic.py. Please, resolve it to run your app.
[flow] 2022-09-01T08:53:04.692Z Traceback (most recent call last):
[flow] 2022-09-01T08:53:04.692Z   File "examples/1_app_agnostic.py", line 5, in <module>
[flow] 2022-09-01T08:53:04.692Z     from lightning_hpo import Sweep
[flow] 2022-09-01T08:53:04.692Z   File "/content/venv/lib/python3.8/site-packages/lightning_hpo/__init__.py", line 22, in <module>
[flow] 2022-09-01T08:53:04.692Z     from lightning_hpo.components.sweep import Sweep  # noqa: E402
[flow] 2022-09-01T08:53:04.692Z   File "/content/venv/lib/python3.8/site-packages/lightning_hpo/components/sweep.py", line 5, in <module>
[flow] 2022-09-01T08:53:04.692Z     from lightning.app.components.python.tracer import Code
[flow] 2022-09-01T08:53:04.692Z ImportError: cannot import name 'Code' from 'lightning.app.components.python.tracer' (/content/venv/lib/python3.8/site-packages/lightning/app/components/python/tracer.py)
[flow] 2022-09-01T08:53:05.113Z INFO: Found dead components ['Flow', 'Server', 'root.hi_plot'], Exiting execution!!!

```

### To Reproduce

 lightning run app examples/1_app_agnostic.py --cloud

**Comment by tchaton** [comment]
This wasn't using the latest version of lightning.

Resolved by updating the docs installation protocol.
